import {blankColumn, Table} from "../table/tableFns.ts";
import {evalExpression} from "./evalExpression.ts";

/**
 * Return a column of values generated by evaluating the given expression with
 * the given variable bindings (in tabular form.)
 * @param expression
 * @param bindingTable
 * @throws Error on encountering a parse error.
 */
export function evaluateWithBindings(expression: string, bindingTable: Table): Table {
	try {
		return bindingTable.map(
			(row) => [evalExpression(expression,row) ?? false]
		)
	} catch (e) {
		return blankColumn(bindingTable.length);
	}
}
